version: 2

workflows:
  version: 2
  pipeline:
    jobs:
      - node-step

jobs:
  node-step:
    docker:
      - image: smitkumarpatel/sample
    steps:
      - run:
          name: Cat
          command: cat /etc/os-release
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: PWD
          command: pwd
      - run:
          name: list
          command: ls -a
      - run:
          name: list
          command: ls -ld /user/src/app
      - run:
          name: Cat
          command: cat /etc/os-release
