version: 2

workflows:
  version: 2
  pipeline:
    jobs:
      - node-step

jobs:
  node-step:
    docker:
      - image: smitkumarpatel/sample
        auth:
          username: $USERNAME
          password: $PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: npm start
