version: 2

workflows:
  version: 2
  pipeline:
    jobs:
      - setup
      - node-step

ubu-img: &ubu-img
  docker:
    - image: alpine

jobs:
  setup:
    <<: *ubu-img
    steps:
      - run:
          name: Cat
          command: cat /etc/os-release

  node-step:
    <<: *ubu-img
    docker:
      - image: smitkumarpatel/sample
    steps:
      - run:
          name: Cat
          command: cat /etc/os-release
      - run:
          name: Install Docker client
          command: apk add docker-cli
      - run:
          name: docker build
          command: docker build -t sample smitkumarpatel/sample
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: docker run
          command: docker run -it --rm --entrypoint bash smitkumarpatel/sample
      - run:
          name: run node
          command: npm start
      - run:
          name: Cat
          command: cat /etc/os-release
